import type { BentoEvent } from "./event-bento-card";

const colors: BentoEvent["color"][] = ["amber", "sky", "rose"];

export const mockEvents: BentoEvent[] = [
  {
    id: "1",
    title: "Coffee & Code",
    date: "2026-06-30",
    time: "14:00–15:30",
    location: "Starbucks, Невский",
    color: "amber",
  },
  {
    id: "2",
    title: "Morning Brew",
    date: "2026-07-01",
    time: "10:00–11:00",
    location: "Double B",
    color: "sky",
    imageUrl: "/events/vertical1.png",
  },
  {
    id: "3",
    title: "Latte & Learn",
    date: "2026-07-02",
    time: "18:00–19:00",
    location: "Surf Coffee",
    color: "rose",
    imageUrl: "/events/vertical2.png",
  },
  {
    id: "4",
    title: "Espresso Talks",
    date: "2026-07-03",
    time: "12:00–13:00",
    location: "Skuratov Coffee",
    color: "amber",
  },
  {
    id: "5",
    title: "Flat White Friday",
    date: "2026-07-04",
    time: "17:30–19:00",
    location: "Starbucks, Московский",
    color: "sky",
  },
  {
    id: "6",
    title: "Cappuccino & Chat",
    date: "2026-07-05",
    time: "11:00–12:30",
    location: "Double B",
    color: "rose",
  },
  {
    id: "7",
    title: "Cold Brew Walk",
    date: "2026-07-06",
    time: "09:00–10:00",
    location: "Surf Coffee",
    color: "amber",
  },
  {
    id: "8",
    title: "Matcha Meetup",
    date: "2026-07-08",
    time: "15:00–16:00",
    location: "Skuratov Coffee",
    color: "sky",
  },
  {
    id: "9",
    title: "Pour Over Party",
    date: "2026-07-10",
    time: "13:00–14:30",
    location: "Starbucks, Невский",
    color: "rose",
  },
  {
    id: "10",
    title: "Barista Basics",
    date: "2026-07-12",
    time: "16:00–17:30",
    location: "Double B",
    color: "amber",
  },
  {
    id: "11",
    title: "Sunday Slow Coffee",
    date: "2026-07-13",
    time: "10:30–12:00",
    location: "Surf Coffee",
    color: "sky",
  },
  {
    id: "12",
    title: "Night Owl Espresso",
    date: "2026-07-15",
    time: "20:00–21:00",
    location: "Skuratov Coffee",
    color: "rose",
  },
  {
    id: "13",
    title: "Raf & Relax",
    date: "2026-07-18",
    time: "19:00–20:30",
    location: "Starbucks, Невский",
    color: "amber",
  },
].map((event, index) => ({
  ...event,
  color: colors[index % colors.length],
}));
